language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="pur_beurre.pur_beurre.settings.travis"

script:
  - pur_beurre.manage.py test
